name: Build Docker Image

on:
  push:
    branches:
      - main  # Déclenche l'action seulement pour la branche "main"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code dans le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure Docker pour s'authentifier sur DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build l'image Docker avec deux tags: un pour le SHA du commit et un pour latest
      - name: Build the Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/chatbot-maisonnette:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/chatbot-maisonnette:latest

      # Pousse l'image Docker sur DockerHub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-maisonnette:${{ github.sha }}
      - name: Push the Docker image with latest tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-maisonnette:latest
